language: php
php:
    - 8.0
    
env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        
install:
    - travis_retry composer update ${COMPOSER_FLAGS}
    
script:
  - vendor/bin/phpunit --testdox tests